[tool.poetry]
name = "openbb-tmx"
version = "1.1.0"
description = "Unofficial TMX data provider extension for the OpenBB Platform - Public Canadian markets data for Python and Fast API."
authors = ["DeeLeeRamone <deeleeramone@proton.me>"]
readme = "README.md"
packages = [{ include = "openbb_tmx" }]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp-client-cache = "^0.10.0"
aiosqlite = "^0.19.0"
random-user-agent = "^1.0.1"
pandas-market-calendars = "^4.3.3"
openbb-core = "^1.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
tmx = "openbb_tmx:tmx_provider"
